import { NgModule } from '@angular/core';

import {
    MatButtonModule, 
    MatCheckboxModule,
    MatInputModule,
    MatIconModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatMenuModule,
    MatChipsModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatExpansionModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatDialogModule,
    MatRadioModule,
    MatAutocompleteModule,
} from '@angular/material';

@NgModule({
  imports: [
      MatButtonModule,
      MatProgressSpinnerModule, 
      MatAutocompleteModule,
      MatCheckboxModule,
      MatInputModule,
      MatMenuModule,
      MatIconModule,
      MatListModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatSelectModule,
      MatSlideToggleModule,
      MatTableModule,
      MatPaginatorModule,
      MatSortModule,
      MatChipsModule,
      MatExpansionModule,
      MatSnackBarModule,
      MatProgressBarModule,
      MatDialogModule,
      MatRadioModule,
  ],
  exports: [
      MatButtonModule,
      MatProgressSpinnerModule, 
      MatAutocompleteModule,
      MatCheckboxModule,
      MatInputModule,
      MatIconModule,
      MatListModule,
      MatMenuModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatSelectModule,
      MatSlideToggleModule,
      MatTableModule,
      MatPaginatorModule,
      MatSortModule,
      MatChipsModule,
      MatExpansionModule,
      MatSnackBarModule,
      MatProgressBarModule,
      MatDialogModule,
      MatRadioModule,
  ],
  
  
})
export class AppMaterialModule {}